
const courses = [
    {code:'ICT10001', desc:'Problem Solving with ICT', cp:12.5, type:'Core'},
    {code:'COS10005', desc:'Web Development', cp:12.5, type:'Core'},
    {code:'INF10003', desc:'Introduction to Business Information Systems', cp:12.5, type:'Core'},
    {code:'INF10002', desc:'Database Analysis and Design', cp:12.5, type:'Core'},
    {code:'COS10009', desc:'Introduction to Programming', cp:12.5, type:'Core'},
    {code:'INF30029', desc:'Information Technology Project Management', cp:12.5, type:'Core'},
    {code:'ICT30005', desc:'Professional Issues in Information Technology', cp:12.5, type:'Core'},
    {code:'ICT30001', desc:'Information Technology Project', cp:12.5, type:'Core'},
    {code:'COS20001', desc:'User-Centred Design', cp:12.5, type:'Software Development'},
    {code:'TNE10005', desc:'Network Administration', cp:12.5, type:'Software Development'},
    {code:'COS20016', desc:'Operating System Configuration', cp:12.5, type:'Software Development'},
    {code:'SWE20001', desc:'Development Project 1 - Tools and Practices', cp:12.5, type:'Software Development'},
    {code:'COS20007', desc:'Object Oriented Programming', cp:12.5, type:'Software Development'},
    {code:'COS30015', desc:'IT Security', cp:12.5, type:'Software Development'},
    {code:'COS30043', desc:'Interface Design and Development', cp:12.5, type:'Software Development'},
    {code:'COS30017', desc:'Software Development for Mobile Devices', cp:12.5, type:'Software Development'},
    {code:'INF20012', desc:'Enterprise Systems', cp:12.5, type:'Systems Analysis'},
    {code:'ACC10007', desc:'Financial Information for Decision Making', cp:12.5, type:'Systems Analysis'},
    {code:'INF20003', desc:'Requirements Analysis and Modelling', cp:12.5, type:'Systems Analysis'},
    {code:'ACC20014', desc:'Management Decision Making', cp:12.5, type:'Systems Analysis'},
    {code:'INF30005', desc:'Business Process Management', cp:12.5, type:'Systems Analysis'},
    {code:'INF30003', desc:'Business Information Systems Analysis', cp:12.5, type:'Systems Analysis'},
    {code:'INF30020', desc:'Information Systems Risk and Security', cp:12.5, type:'Systems Analysis'},
    {code:'INF30001', desc:'Systems Acquisition & Implementation Management', cp:12.5, type:'Systems Analysis'},
    {code:'ECO10004', desc:'Principles of Microeconomics', cp:12.5, type:'Economics'},
    {code:'ECO10003', desc:'Principles of Macroeconomics', cp:12.5, type:'Economics'},
    {code:'ECO20001', desc:'Intermediate Microeconomics', cp:12.5, type:'Economics'},
    {code:'ECO20002', desc:'Intermediate Macroeconomics', cp:12.5, type:'Economics'},
    {code:'ECO30001', desc:'Economic Theory and Policy', cp:12.5, type:'Economics'},
    {code:'ECO30004', desc:'International Economics', cp:12.5, type:'Economics'},
    {code:'FIN10002', desc:'Fundamentals of Finance', cp:12.5, type:'Finance'},
    {code:'FIN20001', desc:'Corporate Finance', cp:12.5, type:'Finance'},
    {code:'FIN20002', desc:'Investments', cp:12.5, type:'Finance'},
    {code:'FIN30001', desc:'Financial Modeling and Valuation', cp:12.5, type:'Finance'},
    {code:'FIN30002', desc:'Derivative Securities', cp:12.5, type:'Finance'},
    {code:'MAT10007', desc:'Calculus 1', cp:12.5, type:'Mathematics'},
    {code:'MAT10008', desc:'Calculus 2', cp:12.5, type:'Mathematics'},
    {code:'MAT20009', desc:'Linear Algebra', cp:12.5, type:'Mathematics'},
    {code:'MAT20010', desc:'Probability and Statistics', cp:12.5, type:'Mathematics'},
    {code:'MAT30011', desc:'Real Analysis', cp:12.5, type:'Mathematics'},
    {code:'MAT30012', desc:'Abstract Algebra', cp:12.5, type:'Mathematics'},
    {code:'PHY10001', desc:'Physics 1', cp:12.5, type:'Physics'},
    {code:'PHY10002', desc:'Physics 2', cp:12.5, type:'Physics'},
    {code:'PHY20001', desc:'Electromagnetism', cp:12.5, type:'Physics'},
    {code:'PHY20002', desc:'Quantum Mechanics', cp:12.5, type:'Physics'},
    {code:'PHY30001', desc:'Astrophysics', cp:12.5, type:'Physics'}
]